openapi: 3.0.0

info:
  title: PDF generator API
  description: PDF generator API
  version: 1.0.0

components:
  requestBodies:
    Print:
      content:
        application/json:
          schema:
            type: object
            properties:
              source:
                type: string
                description: Optional string to define the source of request
                example: crude-oil-price-report
              html:
                type: string
                description: HTML layout to print
                example: '<html><head></head><body>test</body></html>'
              pdfSettings:
                type: object
                description: Optional settings passed to page.pdf() call
                example: { width: '100px' }
            required:
              - html

  responses:
    Success:
      description: Generated PDF file.
      content:
        application/pdf:
          schema:
            type: string
            format: binary

    BadRequest:
      description: Bad request.

    ServerError:
      description: Server error.

tags:
  - name: Pdf

paths:
  /print:
    post:
      summary: Prints PDF page from html layout (chrome v83 by default).
      description: Prints PDF page from html layout (chrome v83 by default).
      tags:
        - Pdf
      requestBody:
        $ref: '#/components/requestBodies/Print'
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'

  /print/chrome/v81:
    post:
      summary: Prints PDF page from html layout using chrome v81.
      description: Prints PDF page from html layout using chrome v81.
      tags:
        - Pdf
      requestBody:
        $ref: '#/components/requestBodies/Print'
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'

  /print/chrome/v83:
    post:
      summary: Prints PDF page from html layout using chrome v83.
      description: Prints PDF page from html layout using chrome v83.
      tags:
        - Pdf
      requestBody:
        $ref: '#/components/requestBodies/Print'
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
